name: Run GitHub Data Collection Script

on:
  # This workflow will run every time you push changes to the repository
  push:
    branches:
      - main

  # You can also trigger the workflow manually from the GitHub Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    # Step 4: Run the Python script
    - name: Run the script
      run: |
        python 'github_api_data collection.py'
